name: api_fussball_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/api-fussball/api-dart

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.0.0
  html: ^0.15.4
  xpath_selector_html_parser: ^3.0.1
  isar: ^3.1.0+1
  xml: ^6.3.0
  sprintf: ^7.0.0
  email_validator: ^2.1.17


dev_dependencies:
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  lints: ^2.0.0
  test: ^1.21.0

